### ISSUE TITLE
Feature Request: Checksum of settings before trying to upload on close

### ISSUE THREAD

**Issue by Ryan00793** [evemondevteam/evemon#1]
I think the cloud service built in is a cool feature and would like to ask you guys to check the md5 of start config vs the end, or even just a bool that says hey we changed something you should upload at the end sorta thing so that the program closes with out uploading if it doesn't have to.

**Comment by JimiC** [comment]
There is no point in doing that. Simply because when EVEMon starts it checks the EVE serve status and saves the update datetime in the settings file. That means that immediately the md5 is different with the one stored in the cloud. Even if you start and close EVEMon immediately the settings file have changed.
