### ISSUE TITLE
Error while waching skill queue

### ISSUE THREAD

**Issue by shmupsik** [evemondevteam/evemon#18]
Here is error message:

---

EVEMon Version: 3.0.2.4644
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.10586.0
Executable Path: "D:\Data\Desktop\EVE\EVEMon\EVEMon.exe" 

System.DivideByZeroException: Попытка деления на нуль.
   в EVEMon.CharacterMonitoring.CharacterSkillsQueueList.lbSkillsQueue_MouseWheel(Object sender, MouseEventArgs e) в EVEMon\CharacterMonitoring\CharacterSkillsQueueList.cs:строка 439
   в System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
   в System.Windows.Forms.Control.WmMouseWheel(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ListBox.WndProc(Message& m)

**Comment by elliena-bulmer** [comment]
There's a few controls that will need to be fixed in order to prevent this crash. At least, it should be easy to fix.

The affected files are:
CharacterContactList.cs
CharacterEmploymentHistoryList.cs
CharacterKillLogList.cs
CharacterMedalsList.cs
CharacterSkillsList.cs
CharacterSkillsQueueList.cs
CharacterStandingsList.cs
KillReportFittingContent.cs

In each of them, we try to divide by the delta of the scrolling. This delta could be 0 so we just need to add a check for this case.

**Comment by elliena-bulmer** [comment]
Issue should be fixed with f338a9c 
it's not in the main branch yet tho. might have to wait an official release or grab the changes from my branch and build it locally. Either way, please let me know if it's still not working on your side.
