### ISSUE TITLE
Update via auto-update fails to download

### ISSUE THREAD

**Issue by init-000** [evemondevteam/evemon#46]
After starting EVEMON I receive the message that a new version is available. I click on the "Update..." button (like for all previous versions) and the download progress bar is displayed for about 1 second after which I receive the error message:

"File failed to download correctly, do you wish to try again?"

I re-tried countless times and also waited a full 24h and tried again but I'm still receiving the same error message. 

Is there a problem with the auto-update? Or do you have any other ideas? 

I'm not experiencing any other issues with downloads or with my internet connection. It seems to be a problem exclusive to EVEMON auto-update. 

For the time being I can simply manually update my installation but I still wanted to inform you so you can fix it for future releases. 

Keep up the good work.

**Comment by Ashilta** [comment]
We experienced this problem when we first published the latest patch, is something had gone amiss in the process of updating the MD5 checksums to be compared with the files being downloaded. It was resolved by publishing a new patch, but for some reason you've not received this. 

To confirm, are you closing EVEMon between attempts, or is EVEMon running on a PC that is never off and so EVEMon is always running? Restarting EVEMon should resolve the problem. Please let me know if it doesn't.

**Comment by init-000** [comment]
I was shutting down EVEMon between attempts so it doesn't seem to be related to that problem. 

Sadly I have now updated my installation by hand to the newest version so I can't repeat the test anymore. 

I'll try on my laptop this evening (which is still running the previous version) and will update this ticket if the problem persists.

**Comment by init-000** [comment]
Ok, I can reproduce the issue on my other computer:

I currently have EVEMon v. 3.0.2.4644 installed. The auto-update feature is suggesting that I update to v. 3.0.3.4658

Clicking on "Update..." opens the "Downloading Update..." progress bar, which remains at 0%. After less then 1 second I receive the aforementioned error message: 

File failed to download correctly, do you wish to try again?
Yes   No   

Repeating the attempt yields the same result. 

Just to make absolutely certain I shutdown EVEMon and checked in Task Manager to ensure that the process was really gone. Relaunching EVEMon and repeating the auto-update attempt after that still gives me the same behavior. 

I also tried to right click EVEMon -> Run as Administrator but I'm still getting the same error. 

I'm running Windows 10 (64bit) on this computer and am using an administrator account. On my other computer I run Windows 7 (64bit) and also use an administrator account. 

I never had any issues with EVEMon auto-update in the past (on either of my systems). 

I will gladly hold off on updating my version by hand for now if that helps you with finding the issue. Please let me know if you would like any further information or testing from me.

**Comment by JimiC** [comment]
I also tried it and had no problem. Probably your anti-virus is blocking the download.

**Comment by init-000** [comment]
I guess that's possible but I find it strange that my anti-virus software (Microsoft Security Essentials on Windows 7, Windows Defender on Windows 10, both with updated definitions) should suddenly start blocking EVEMon auto-update without giving any kind of notification or message. It never did so in the past (and as I said: I didn't change anything in the settings of my computers or anti-virus recently). 

I also checked the logs of Windows Defender and couldn't find any indication that anything was blocked. 

Also, correct me if I'm wrong but wouldn't the anti-virus software normally only prevent execution of the file and not block the download? I never experienced that before (and I have downloaded dodgy files in the past that then got detected as a potential threat by the anti-virus software but the actual download wasn't prevented - only the execution). 

Also, wouldn't it be a good idea to ensure that a common anti-virus software like Windows Defender doesn't give false positives for EVEMon (if this is indeed the cause of the problem)? I imagine this wouldn't exactly increase the trust in EVEMon for potential new users... 

Anyway, if you don't want to investigate this issue further then just close the ticket and I'll update my version by hand and we'll hope for the best.

**Comment by JimiC** [comment]
@init-000 It was a wild guess. You are right. I have never come across an anti-virus that stopped the download, but you never mentioned the anti-virus software you are using, so it was worth a try. You can never be sure what kind of software those "genius" offer. The only thing that ever gave us issues, beside EVEMon itself, where the anti-virus software.

Strangely, I tested the update mechanism on a Win7 and Win10, with the same anti-virus software as you. Everything worked fine. Looks like your issue is an isolated case, and the only one who can debug it is you, as it's probably something on your side. Believe me when I say, if it was an EVEMon issue we would had known in an instance, as EVEMon gets downloaded tens of thousands of times, and our EVE forums and email would be buzzing about it.

Regarding your question about dealing with the "false-positive" issue, we never liked the idea going through MS channels to certify EVEMon and use `msi`. Too much hassle for a hobby project. I don;t know if @Ashilta wants to go through with it but me and my predecessors agreed to stick with `NSIS`. Maybe `Squirrel` could be an alt choice, but I personally prefer `NSIS`.

**Comment by Ashilta** [comment]
Morning,

Jimi has beaten me to posting by minutes. I'm almost certain that the Anti-Virus is not a problem, as I'm also using Windows/Microsoft AV products on my Windows 10 devices and have had no issues.

The conceivable problem I can think of is that for some reason, when EVEMon connects to the datastore to get the latest patch file, it's still getting the 'broken' version, rather than the one we replaced it with which should've resolved the issue. I can't think of any obvious way around this - it's the responsibility of the repository to serve the 'correct' version of this.

If updating EVEMon manually resolves the issue for you then I think this is the only sensible course of action at this time. If, however, this issue repeats itself in the next release then we'll need to take a closer look. As Jimi says, you're currently the only observer of this behaviour, as everyone else that experienced it had the issue resolved with the deployment of the new patch, and so I'm at a loss to explain this.

**Comment by init-000** [comment]
Thanks for the fast responses and all the effort @Ashilta and @JimiC ! 

I will gladly update EVEMon by hand (which already resolved the issue on my first machine without any trouble). 

Please keep up the great work you are doing on EVEMon! EVE just wouldn't be the same without you! :-)

Cheers!
init-000

-> Ticket closed.
