### ISSUE TITLE
"Account Status Expired" display on Omega character

### ISSUE THREAD

**Issue by TheFlow0360** [evemondevteam/evemon#66]
I recently reinstalled EVEMon on another PC where I didn't enable the Safe Mode. Below my Avatar there is now a red line showing "Account Status: Expired" even though technically accounts can no longer expire plus this isn't even an Alpha Clone. Is this just incompatibility with the Omega-System or is this a bug?

The expiration date should match the last time my account expired, I paused the game for some time and came back when the new subscription system was already running. Wild guess: when an account expired before Omega took over, this happens, if it was subscribed properly it doesn't. Don't have a way to confirm that, may be worth testing.

![Preview](https://user-images.githubusercontent.com/7249679/28521693-19dea688-7075-11e7-946c-e1705331cfae.png)

**Comment by TheFlow0360** [comment]
I tested this with the current master, and there I get "Account Status: Alpha" even though it should be Omega...

![Preview](https://user-images.githubusercontent.com/7249679/28524226-de1f0e98-707f-11e7-945a-1850cd47bbe0.png)

The `Character.CharacterStatus` is `AccountStatusType.Alpha` so the UI is working correctly, I'll have a look where to wrong data comes from.

**Comment by TheFlow0360** [comment]
ok, so the only criterion for the CharacterStatus is the Property `AccountExpires` on an APIKey, which in turn is retrieved directly from the API when getting a `SerializableAPIAccountStatus` through the field `PaidUntil`.

The `PaidUntil` comes directly from the API. I tested the particular call with PostMan, resulting in this output:

    <?xml version='1.0' encoding='UTF-8'?>
    <eveapi version="2">
        <currentTime>2017-07-24 13:21:26</currentTime>
        <result>
            <paidUntil>2016-10-06 18:08:44</paidUntil>
            <createDate>2013-07-19 17:51:17</createDate>
            <logonCount>192</logonCount>
            <logonMinutes>11098</logonMinutes>
            <rowset name="multiCharacterTraining" key="trainingEnd" columns="trainingEnd" />
        </result>
        <cachedUntil>2017-07-24 13:49:01</cachedUntil>
    </eveapi>

So either the API just doesn't work correctly, or this is an deprecated call an there is a new one since the Alpha/Omega stuff started.

**Comment by Ashilta** [comment]
The problem is unfortunately simple, but sadly difficult to resolve.

The XML API doesn't know about Alpha/Omega. As you've identified, it knows when you've paid until, and subsequently EVEMon can determine whether or not your account is paid (active) or unpaid (expired).  CCP have made a _conscious decision_ to not include an endpoint in either CREST or ESI to indicate whether an account is an Alpha or an Omega account, as their view is that if compromised, this _might_ provide an insight into the personal circumstances of the player. Personally I disagree, but that is their view.

Instead, I/we need to figure out a way of determining whether an account is Alpha or Omega. There are options, like whether an Omega skill is being trained, the rate at which skill points are increasing, current ship etc, but there's no definitive endpoint for "is this account omega?"

**Comment by TheFlow0360** [comment]
I checked the [reference page](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/account/account_accountstatus.html) and there doesn't seem to be any other way to get information. I guess it'S because the XML API is deprecated...

**Comment by TheFlow0360** [comment]
@Ashilta ok thanks for the info. Maybe the expiration should be removed from UI or even better from the program entirely (though this would be quite a lot refactoring)

**Comment by Ashilta** [comment]
You're right, it's a lot of refactoring. There are a plethora if difficulties in trying to get the new APIs integrated with EVEMon; for a start, the idea of "accounts" is entirely lost on the ESI API. Account subscription is no longer a thing as far as the APIs are concerned, everything is character based when dealing with "players."

**Comment by TheFlow0360** [comment]
Yeah probably it would be faster to rewrite the application instead of trying to refactor the whole structure... API changes are really a handful :/
